workflowVersion: 1.0.0
sources:
    my-first-source:
        inputs:
            - location: https://api.dub.sh
targets:
    my-first-target:
        target: typescript
        source: my-first-source
        output: ./typescript
